name: Update Membership Counts

on:
  push:
    branches:
      - test/github-action
  schedule:
    # Run on the first of every month
    - cron: 0 0 1 * *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v1
    - name: Install dependencies and run script
      run: |
        sudo apt-get update && sudo apt-get install -y python3 python3-pip
        sudo pip3 install requests
        python3 scripts/update_counts.py
    - name: Checkout New Branch
      env:
        GITHUB_TOKEN: "{{ secrets.GITHUB_TOKEN }}"
      run: |
        echo "GitHub Actor: ${GITHUB_ACTOR}"
        git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git branch
        git checkout -b update/member-count-$(date '+%Y-%m-%d')
        git branch
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add _data/memberCounts.csv

        #git remote set-url origin git@github.com:${GITHUB_ACTOR}/usrse.github.io.git
        git commit -m "Automated deployment to update Member Counts $(date '+%Y-%m-%d')" --allow-empty
        #git push origin update/member-count-$(date '+%Y-%m-%d')
        GIT_TRACE=1 git push origin update/member-count-$(date '+%Y-%m-%d') --verbose

    - name: Open pull request
      uses: "vsoch/pull-request-action@master"
      env:
        GITHUB_TOKEN: "{{ secrets.GITHUB_TOKEN }}"
        BRANCH_PREFIX: = "update/member-count"
        PULL_REQUEST_BRANCH: "master"
